---
- name: Setting Up IPA Server
  hosts: ipa
  strategy: free
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=ipa.example.com
  - name: Changing User Password
    shell: echo vagrant | sudo passwd vagrant --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Adjusting sftp
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Subsystem'
      line: 'Subsystem sftp internal-sftp'
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6 localhost6.localdomain6\n192.168.55.4 repo.example.com repo\n192.168.55.5 ipa.example.com ipa\n192.168.55.6 system1.example.com system1"
      force: yes
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/rpms.repo
      state: touch
      mode: 0755
  - name: Building Repo File. Installing Packages...
    copy:
      dest: /etc/yum.repos.d/rpms.repo
      content: "[rpms]\nname=rpms\nbaseurl=http://repo/rpms\ngpgcheck=0\nenabled=1"
  - name: Packages Installed
    yum:
      name:
        - ipa-server
        - ipa-server-dns
        - chrony
  - name: Configuring network
    shell: nmcli con mod 'System eth1' ipv4.addresses 192.168.55.5/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Restarted Network
    service: name=NetworkManager state=restarted
  - name: Starting services
    service: name=firewalld state=started enabled=yes
  - name: Enabling Firewall Services. Configuring IPA server...(Est. Time - 7 minutes)
    firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - http
      - https
      - ntp
      - dns
      - kerberos
      - ldap
      - ldaps
      - ftp
      - nfs
      - rpc-bind
      - ldap
      - ldaps
      - mountd
  - name: Configuring IPA Server    
    block: 
      - name: Finishing IPA server Configuration
        command: ipa-server-install --setup-dns --allow-zone-overlap --mkhomedir --auto-reverse -a 'password' --hostname=ipa.example.com -r EXAMPLE.COM -p 'password' -n example.com -U --forwarder 8.8.8.8
    rescue:
      - debug:
          msg: "An error occured during the IPA server installation, reverting back..."
      - name: Uninstalling Failed IPA Configuration
        command: ipa-server-install --uninstall
  - name: Creating NFS shares
    copy:
      content: "/home/ldap/dave   192.168.55.6(rw)\n/home/ldap/lisa   192.168.55.6(rw)"
      dest: /etc/exports
      force: yes
  - name: Starting services
    service: name={{item}} enabled=true state=started
    with_items:
      - httpd
      - chronyd
      - nfs-server
  - name: Creating LDAP User Directory
    file:
      path: /home/ldap
      state: directory
      mode: '0755'
  - name: Restarting NFS Server
    service: name=nfs-server state=restarted
  - name: Authenticating KRB5 Database
    expect:
      command: kinit admin
      responses:
        (.*)Password for admin@EXAMPLE.COM(.*): 'password'
    tags: krb
  - name: Setting LDAP User Home Directory Location
    command: ipa config-mod --homedirectory /home/ldap
    tags: krb
  - name: Adding IPA user 'dave'
    ipa_user:
        name: dave
        state: present
        krbpasswordexpiration: '20200119235959'
        givenname: dave
        sn: dave
        mail:
        - dave@example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: '1001'
        gidnumber: '1000'
        ipa_host: ipa.example.com
        ipa_user: admin
        ipa_pass: password
  - name: Signing Into Dave
    command: su - dave
  - name: Creating Dave Test File
    copy:
      content: "This is Dave's test file"
      dest: /home/ldap/dave/davetest.txt
      owner: dave
      group: dave
  - name: Fixing Dave's Home Directory Permissions
    file:
      path: /home/ldap/dave
      state: directory
      recurse: yes
      owner: dave
      group: dave
  - name: Adding IPA user 'lisa'
    ipa_user:
        name: lisa
        state: present
        krbpasswordexpiration: '20200119235959'
        givenname: lisa
        sn: lisa
        mail:
        - lisa@example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: '1002'
        gidnumber: '1001'
        ipa_host: ipa.example.com
        ipa_user: admin
        ipa_pass: password
  - name: Signing Into Lisa
    command: su - lisa
  - name: Creating Lisa Test File
    copy:
      content: "This is Lisa's test file"
      dest: /home/ldap/lisa/lisatest.txt
      owner: lisa
      group: lisa
    remote_user: lisa
  - name: Fixing Lisa's Home Directory Permissions
    file:
      path: /home/ldap/lisa
      state: directory
      recurse: yes
      owner: lisa
      group: lisa
  - name: Copying CA CERT
    copy:
      src: /etc/ipa/ca.crt
      dest: /var/www/html/ca.crt
      remote_src: yes
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #             _         _         _          
         #           /\ \      /\ \      / /\        
         #           \ \ \    /  \ \    / /  \       
         #           /\ \_\  / /\ \ \  / / /\ \      
         #          / /\/_/ / / /\ \_\/ / /\ \ \     
         #         / / /   / / /_/ / / / /  \ \ \    
         #        / / /   / / /__\/ / / /___/ /\ \   
         #       / / /   / / /_____/ / /_____/ /\ \  
         #   ___/ / /__ / / /     / /_________/\ \ \ 
         #  /\__\/_/___/ / /     / / /_       __\ \_\
         #  \/_________\/_/      \_\___\     /____/_/
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         "
  - name: Adjusting Services then Rebooting
    selinux:
      state: permissive
      policy: targeted
...
