---
- name: Setting Up Repo Server
  hosts: repo
  strategy: free
  gather_facts: false
  ignore_errors: yes
  tasks:
  - name: Setting Hostname
    hostname: name=repo.example.com
  - name: Adjusting sftp
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Subsystem'
      line: Subsystem  sftp internal-sftp
  - name: Configuring network
    shell: nmcli con mod 'System enp0s8' ipv4.addresses '192.168.55.4/24 192.168.55.1' ipv4.dns 8.8.8.8 ipv4.method manual
  - name: Restarting Network
    service: name=NetworkManager state=restarted
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6localhost6.localdomain6\n192.168.55.4 repo.example.com repo\n192.168.55.5 ipa.example.com ipa\n192.168.55.6 system1.example.com system1'
      force: yes
  - name: Starting Services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - firewalld
      - httpd
  - name: Enabling Firewall Services
    firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: yes
      permanent: yes
    with_items:
      - http
      - https
      - ntp
      - dns
      - kerberos
      - ldap
      - ldaps
      - ftp
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #           _          _           _         _       
         #          /\ \       /\ \        /\ \      /\ \     
         #         /  \ \     /  \ \      /  \ \    /  \ \    
         #        / /\ \ \   / /\ \ \    / /\ \ \  / /\ \ \   
         #       / / /\ \_\ / / /\ \_\  / / /\ \_\/ / /\ \ \  
         #      / / /_/ / // /_/_ \/_/ / / /_/ / / / /  \ \_\ 
         #     / / /__\/ // /____/\   / / /__\/ / / /   / / / 
         #    / / /_____// /\____\/  / / /_____/ / /   / / /  
         #   / / /\ \ \ / / /______ / / /     / / /___/ / /   
         #  / / /  \ \ / / /_______/ / /     / / /____\/ /    
         #  \/_/    \_\\/__________\/_/      \/_________/     
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         "
         